spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reconciliation?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  h2:
    console:
      enabled: true
      path: /h2-console
      
jwtDetails:
  secret: FGSJGKSJDLKFJDFLKJDSFDSJFLKJDFLKDFJSDLKJFGSJGKSJDLKFJDFLKJDSFDSJFLKJDFLKDFJSDLKJFGSJGKSJDLKFJDFLKJDSFDSJFLKJDFLKDFJSDLKJFGSJGKSJDLKFJDFLKJDSFDSJFLK
  expiration: 86400000
logging:
  file:
    name: logs/app.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/%d{yyyy-MM, aux}/app.%d{yyyy-MM-dd}.%i.log
      max-file-size: 100MB
      total-size-cap: 10GB
server:
  port: 8080
